// Authentication module keywords
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const AUTH_CHECKED = "AUTH_CHECKED";
export const FETCH_PROFILE_PENDING = 'FETCH_PROFILE_PENDING';
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';
export const SET = "SET";
export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';
export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE';
export const FETCH_EMPLOYEES = 'FETCH_EMPLOYEES';

// Leave module keywords
export const FETCH_LEAVE_REQUEST = 'FETCH_LEAVE_REQUEST';
export const ADD_LEAVE_REQUEST = 'ADD_LEAVE_REQUEST';
export const RESPOND_TO_LEAVE_REQUEST = 'RESPOND_TO_LEAVE_REQUEST';

// App module keywords
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const TOGGLE_DIALOG = "TOGGLE_DIALOG";
export const TOGGLE_NOTIFICATION = "TOGGLE_NOTIFICATION";

// Ticket Module
export const ADD_TICKET = 'ADD_TICKET'
export const FETCH_TICKETS = 'FETCH_TICKETS'
export const CLOSE_TICKET = 'CLOSE_TICKET'

// Department Module
export const ADD_DEPARTMENT = 'ADD_DEPARTMENT'
export const FETCH_DEPARTMENTS = 'FETCH_DEPARTMENTS'

// Performance Review Module
export const ADD_PERFORMANCE_REVIEW = 'ADD_PERFORMANCE_REVIEW'
export const FETCH_PERFORMANCE_REVIEWS = 'FETCH_PERFORMANCE_REVIEWS'
export const FETCH_PERFORMANCE_REVIEWS_BY_REVIEWER = 'FETCH_PERFORMANCE_REVIEWS_BY_REVIEWER'
export const LOADING_STARTED = "LOADING_STARTED"
export const LOADING_DONE = "LOADING_DONE"

// Repository
export const FILE_DOCUMENTS = 'FILE_DOCUMENT';
export const FILE_IMAGES = 'FILE_IMAGES';
export const FILE_VIDEOS = 'FILE_VIDEOS';
export const FILE_OTHERS = 'FILE_OTHERS';

// Department Manager
export const ADD_DEPARTMENT_MANAGER = "ADD_DEPARTMENT_MANAGER"
export const FETCH_DEPARTMENT_MANAGERS = "FETCH_DEPARTMENT_MANAGERS"

// Department Employee
export const ADD_DEPARTMENT_EMPLOYEE = "ADD_DEPARTMENT_EMPLOYEE"
export const FETCH_DEPARTMENT_EMPLOYEES = "FETCH_DEPARTMENT_EMPLOYEES"
export const DELETE_DEPARTMENT_EMPLOYEE = "DELETE_DEPARTMENT_EMPLOYEE"

// Account Module
export const FETCH_EMPLOYEES_ACCOUNTS = "FETCH_EMPLOYEES_ACCOUNTS"
export const DELETE_EMPLOYEE_ACCOUNT = "DELETE_EMPLOYEE_ACCOUNT"
export const RESET_EMPLOYEE_ACCOUNT = "RESET_EMPLOYEE_ACCOUNT"
