import {
  LOGIN,
  LOGOUT,
  AUTH_CHECKED,
  FETCH_PROFILE_PENDING,
  FETCH_PROFILE_SUCCESS,
  SET,
  ADD_EMPLOYEE,
  DELETE_EMPLOYEE,
  UPDATE_EMPLOYEE,
  FETCH_EMPLOYEES,
} from "utils/constants/action-types";

const ActionTypes = {
  AUTH_CHECKED: AUTH_CHECKED,
  LOGOUT: LOGOUT,
  LOGIN: LOGIN,
  FETCH_PROFILE_PENDING: FETCH_PROFILE_PENDING,
  FETCH_PROFILE_SUCCESS: FETCH_PROFILE_SUCCESS,
  SET: SET,
  ADD_EMPLOYEE: ADD_EMPLOYEE,
  DELETE_EMPLOYEE: DELETE_EMPLOYEE,
  UPDATE_EMPLOYEE: UPDATE_EMPLOYEE,
  FETCH_EMPLOYEES: FETCH_EMPLOYEES,
};

const actionCreator = (type, payload = null) => ({ type, payload });
export { ActionTypes, actionCreator };
