import {
  LOGIN,
  LOGOUT,
  AUTH_CHECKED,
  FETCH_PROFILE_PENDING,
  FETCH_PROFILE_SUCCESS,
  FETCH_LEAVE_REQUEST,
  ADD_LEAVE_REQUEST,
  RESPOND_TO_LEAVE_REQUEST,
  TOGGLE_SIDEBAR,
  TOGGLE_DIALOG
} from "utils/constants/action-types";

const ActionTypes = {
  AUTH_CHECKED: AUTH_CHECKED,
  LOGOUT: LOGOUT,
  LOGIN: LOGIN,
  FETCH_PROFILE_PENDING: FETCH_PROFILE_PENDING,
  FETCH_PROFILE_SUCCESS: FETCH_PROFILE_SUCCESS,
  TOGGLE_SIDEBAR: TOGGLE_SIDEBAR,
  FETCH_LEAVE_REQUEST: FETCH_LEAVE_REQUEST,
  ADD_LEAVE_REQUEST: ADD_LEAVE_REQUEST,
  RESPOND_TO_LEAVE_REQUEST: RESPOND_TO_LEAVE_REQUEST,
  TOGGLE_DIALOG: TOGGLE_DIALOG
};

const actionCreator = (type, payload = null) => ({ type, payload });
export { ActionTypes, actionCreator };
